name: Coverity Scan

# We only want to test official release code, not every pull request.
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  coverity:
    runs-on: ubuntu-latest
    container: stefanreinauer/amiga-gcc
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: reinauer/coverity-scan-action@v1
      with:
        configure: --compiler m68k-amigaos-gcc --comptype gcc --template
        email: ${{ secrets.COVERITY_SCAN_EMAIL }}
        token: ${{ secrets.COVERITY_SCAN_TOKEN }}
