name: Generate release files

permissions:
  contents: write
on:
  push:
    tags:
      - "Release-**"
      - "Dev-**"
  workflow_dispatch:

jobs:
  make_software:
    runs-on: ubuntu-latest
    container: liv2/amiga-gcc-amitools
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: true

      - name: Build
        run: |
          git config --global --add safe.directory "*"
          git fetch --prune --unshallow --tags
          make GIT_REF_NAME=${GITHUB_REF_NAME} clean all disk lha

      - uses: actions/upload-artifact@v4.4.0
        with:
          name: software
          path: |
            *.rom
            **/*.adf
            build/*.lha
          if-no-files-found: error

  draft_release:
    runs-on: ubuntu-latest
    needs:
      - make_software

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v4.1.7
        with:
          path: artifacts
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            artifacts/software/*.rom
            artifacts/software/**/*.adf
            artifacts/software/**/*.lha
